//! This build script is necessary because we need to copy the memory.x file to a place the linker
//! can find. This file was generated by Claude sonnet on 2026-03-28

use std::env;
use std::fs;
use std::path::PathBuf;

fn main() {
    let out = PathBuf::from(env::var("OUT_DIR").unwrap());
    fs::copy("memory.x", out.join("memory.x")).unwrap();
    println!("cargo:rustc-link-search={}", out.display()); // Add directory to linker search path
    println!("cargo:rerun-if-changed=memory.x"); // Only run script when memory.x is changed
}
